# Generated by Django 6.0.2 on 2026-02-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
