# Generated by Django 6.0.2 on 2026-02-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
